server:
  port: 80

spring:
  # H2 데이터베이스 연결 정보 설정 (MySQL 호환 모드)
  datasource:
    # SQL 로깅을 위한 log4jdbc 드라이버 적용
    url: jdbc:log4jdbc:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: viny
  sql:
    # 초기 SQL 스크립트 설정
    init:
      encoding: UTF-8
      # 실행 모드 : 내장 데이터베이스 사용시 SQL 스크립트 실행
      mode: EMBEDDED
      # 애플리케이션 구동 시 스키마 및 기본 데이터 자동 생성
      schema-locations:
        - classpath:h2/schema.sql
      data-locations:
        - classpath:h2/data.sql
  h2:
    console:
      path: /h2-console
      enabled: true